---
description: CircleCI executor Molecule
docker:
  - image: '<<parameters.image>>'
parameters:
  image:
    default: ghcr.io/docker-images-mamono210/circleci-executors/molecule-default:latest
    type: string
  resource_class:
    default: medium
    enum: ["small", "medium", "medium+", "large"]
    type: enum
resource_class: '<<parameters.resource_class>>'
