---
- name: Verify
  gather_facts: false
  hosts: all

  tasks:
    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
